### PR TITLE
Update a test to work with theparameterisation of PDMats

### PR DESCRIPTION
**Pull request by KrisDM**
Test is updated to work with parameterization of PDMats, issue #9

### CODE REVIEW

**Comment by tkelman** [comment]
So should the bounds in REQUIRE be adjusted now?

**Comment by kmsquire** [comment]
This fails when the bounds in REQUIRE are adjusted to allow the latest `PDMats` (and therefore, `Distributions`) to install.

@KrisDM, any chance you can update this package to work with the latest `PDMats`?  Anyone who has it installed is stuck with the older versions of `PDMats` and `Distributions`.

**Comment by KrisDM** [comment]
@kmsquire Didn't I fix it already with the above submission? It passed it when I tested it with the new PDMats on my local machine.

**Comment by tkelman** [comment]
Unless you remove the upper bound from `REQUIRE`, Travis will respect it and install an old version of PDMats.

**Comment by KrisDM** [comment]
So you're saying I should remove the upper bound of REQUIRE in this fork before the pull request can be merged?

I won't have time to look at that today, but can try later. Alternatively, if you want to move ahead and remove the upper bound yourself while merging (don't know if that's possible) then please do so. There's only 2 lines of test code which have changed, nothing else.

**Comment by kmsquire** [comment]
I also can't look right now, but I got an error when I tried it last night.

**Comment by tkelman** [comment]
Bump! What's the status here, this package holds a lot of others back if installed, it really needs a new tag that's compatible with the latest versions of the rest of the JuliaStats packages. see https://groups.google.com/forum/#!topic/julia-users/WCgx5mfC6tY

**Comment by KrisDM** [comment]
See my comment in the other thread. ConjugatePriors should be tested (and possibly adapted) to work with the new parameterisation of MvNormal in the Distributions package post 0.9. This pull request was only a temporary 2 line fix to a test, and it's very likely that will be made obsolete by changes required to make it work with the new parameterisation.

**Comment by ararslan** [comment]
Looks like this is no longer necessary after recent updates to the package. Thanks for your hard work here, it's still very much appreciated!

**Pull request closed without merging**
