### PR TITLE
Make tests passing

### PR DESCRIPTION
**Pull request by hassaku**
I bring this module into my use.
And I would like to add this by Pkg.add command but it's not included in METADATA yet.

I fixed tests as passing before I ask you to publish it.
I would appreciate if you give positive consideration to publish.

Tests status is the following.
[Build Status](https://travis-ci.org/hassaku/ConjugatePriors.jl)

### CODE REVIEW

**Comment by lindahua** [comment]
Thanks a lot

**Comment by lindahua** [comment]
I will publish it.

**Comment by lindahua** [comment]
Looks like it remains failing:

```
running conjugates_mvnormal.jl ...
ERROR: LoadError: LoadError: test failed: insupport(ps,ps.μ) && insupport(InverseWishart,ps.Σ.mat)
 in expression: insupport(ps,ps.μ) && insupport(InverseWishart,ps.Σ.mat)
 in error at error.jl:21
 in default_handler at test.jl:30
 in do_test at test.jl:53
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:197
 in anonymous at no file:8
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:197
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /Users/dhlin/.julia/v0.4/ConjugatePriors/test/conjugates_mvnormal.jl, in expression starting on line 86
while loading /Users/dhlin/.julia/v0.4/ConjugatePriors/test/runtests.jl, in expression starting on line 5
```

**Comment by lindahua** [comment]
I will look into this later.

**Comment by lindahua** [comment]
It works well now.

**Comment by lindahua** [comment]
I just published it to METADATA.

**Comment by hassaku** [comment]
Thanks for publishing!

**Pull request merged**
