### PR TITLE
Prevent numerical instability when sampling from Normal-Wishart

### PR DESCRIPTION
**Pull request by krylea**
While using the rand function in normalwishart.jl I noticed that I frequently got errors thrown by Base.LinAlg.cholfact. I tracked this back and it appears that the matrix inv(Lam) ./ nw.kappa sometimes has differences in its off-diagonal elements of ~1e-18, which then get detected as errors when passing this matrix to MvNormal (since julia's linear algebra code has no relative tolerance when checking for symmetry). I inquired about adding such a tolerance to Base.LinAlg.ishermitian but was informed that the choice not to include it was deliberate and that it will not be changed. As such, I am just adding a call to Hermitian here to forcibly symmetrize inv(Lam) ./ nw.kappa (since it should be symmetric anyway) to kill off these discrepancies and prevent numerical errors.
EDIT: Also added the fix to make the NormalWishart type a child of ContinuousMultivarateDistribution rather than ContinuousUnivariateDistribution.

### CODE REVIEW

**Comment by mschauer** [comment]
Relevant test error: https://travis-ci.org/JuliaStats/ConjugatePriors.jl/jobs/363523761#L648

You cannot make a ``Distributions.MvNormal(::Array{Float64,1}, ::Hermitian{Float64,Array{Float64,2}})`` because of known restrictions of the MvNormal type, but I think you
can provide a `PDMats.AbstractPDMat`, see the `PDMats` package (https://github.com/JuliaStats/PDMats.jl) to solve your problem.

**Comment by krylea** [comment]
I believe it should be fixed now. Sorry that it took me a few days.

**Comment by krylea** [comment]
Beneath the pull request I see a box saying "all checks have failed". When I run this locally it does seem to work fine to me. Is there some sort of issue I am not seeing?

**Comment by mschauer** [comment]
ConjugatePriors currently does not support the new version of Julia (nightly), this has nothing to do with you pull request.

**Pull request merged**
